apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: build-watcher
rules:
  - apiGroups:
      - build.knative.dev
    resources:
      - builds
    verbs:
      - get
      - list
      - view
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-watcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-watcher
subjects:
  - kind: ServiceAccount
    name: build-bot
